image: node:lts-alpine3.13

stages:
  - build
  # - test
  - push
  - deploy

# only checks if app builds, build product not used for deployment
build:
  stage: build
  script:
    - npm install
    - npm run-script build

# unit-test:
#   stage: test
#   script:
#     - npm run test

push-image:
  stage: push
  only:
    - master
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout registry.gitlab.com

bridge:
  needs:
    - push-image
  stage: deploy
  only:
    - master
  variables:
    LATEST_IMG_TAG_WEB_CONSOLE: $CI_COMMIT_SHORT_SHA
  trigger: myikaco/test-streams-deploy
